# Generated by Django 3.1.2 on 2021-03-14 00:11

from django.db import migrations, models
import django.db.models.deletion
import face_recognition_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phoneNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='adminEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=face_recognition_api.models.user_directory_path)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_recognition_api.customuser')),
            ],
        ),
    ]
