# Generated by Django 3.1.2 on 2021-03-14 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_api', '0002_auto_20210314_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTime', models.DateTimeField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face_recognition_api.customuser')),
            ],
        ),
    ]
